container:
  image: cirrusci/flutter:latest

android_build_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script: flutter build apk --no-sound-null-safety
  apk_artifacts:
    path: "build/app/outputs/apk/release/app-release.apk"

web_build_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script: flutter build web --no-sound-null-safety
  web_artifacts:
    path: "build/web/*"

linux_build_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - apt-get update && apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libgcrypt20-dev
    - flutter config --enable-linux-desktop
    - flutter build linux --no-sound-null-safety
  linux_artifacts:
    path: "build/linux/*"
