container:
  image: cirrusci/flutter:latest

android_build_task:
  pub_cache:
    folder: ~/.pub-cache
  gradle_cache:
    folder: ~/.gradle/caches
  build_script: flutter build apk
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -rf ~/.gradle/caches/transforms-1
    - rm -rf ~/.gradle/caches/journal-1
    - rm -rf ~/.gradle/caches/jars-3/*/buildSrc.jar
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
  apk_artifacts:
    path: "build/app/outputs/apk/release/app-release.apk"

web_build_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script: flutter build web
  web_artifacts:
    path: "build/web/*"

linux_build_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - apt-get update && apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
    - flutter config --enable-linux-desktop
    - flutter build linux
  linux_artifacts:
    path: "build/linux/*"
