container:
  image: cirrusci/flutter:latest
  
android_build_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script: flutter build apk
  apk_artifacts:
    path: "build/app/outputs/apk/release/app-release.apk"
