container:
  image: cirrusci/flutter:latest
  
android_build_task:
  pub_cache:
    folder: ~/.pub-cache
  update_script:
    - flutter channel master
    - flutter upgrade
  build_script: flutter build apk
