name: nyanya_rocket
description: Save cute mice from dangerous cats!
homepage: https://github.com/CaramelDunes/nyanya_rocket
publish_to: none

version: 2.6.0+61

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  meta: ^1.7.0
  
  path: ^1.8.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274

  nyanya_rocket_base:
    git: https://github.com/CaramelDunes/nyanya_rocket_base.git

  intl: ^0.17.0

  firebase_core: ^2.3.0  
  firebase_auth_platform_interface: ^6.10.1
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0

# Replace with pub.dev packages when fixed.
# https://github.com/invertase/flutterfire_desktop
  firebase_core_desktop:
    git:
      url: https://github.com/NirmalAriyathilake/flutterfire_desktop.git
      path: packages/firebase_core/firebase_core_desktop
  firebase_auth_desktop:
    git:
      url: https://github.com/NirmalAriyathilake/flutterfire_desktop.git
      path: packages/firebase_auth/firebase_auth_desktop

  rive: ^0.9.0

  font_awesome_flutter: ^10.1.0

  shared_preferences: ^2.0.3

  path_provider: ^2.0.1

  uuid: ^3.0.1

  network_info_plus: ^3.0.1

  url_launcher: ^6.0.2

  share_plus: ^6.3.0

  provider: ^6.0.0
  characters: ^1.1.0

  http: ^0.13.0

  slugify: ^2.0.0

  firedart: ^0.9.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/graphics/app_icon.png"
  android: true
  ios: true

  adaptive_icon_background: "#FF673AB7"
  adaptive_icon_foreground: "assets/graphics/adaptive_icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Russo One
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf

  assets:
    - assets/graphics/adaptive_icon_foreground.png
    - assets/graphics/wall.png
    - assets/graphics/wall_cross.png
    - assets/animations/mouse.riv
    - assets/animations/cat.riv
    - assets/animations/drag_arrow.gif
    - assets/animations/swipe_arrow.gif
    - assets/animations/remove_arrow.gif
