name: nyanya_rocket
description: Save cute mice from dangerous cats!
homepage: https://github.com/CaramelDunes/nyanya_rocket
publish_to: none

version: 2.6.0+61

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  meta: ^1.7.0
  
  path: ^1.8.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274

  nyanya_rocket_base:
    git: https://github.com/CaramelDunes/nyanya_rocket_base.git

  intl: ^0.18.1

  firebase_core: ^2.3.0  
  firebase_auth_platform_interface: ^7.2.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  rive: ^0.13.1

  font_awesome_flutter: ^10.1.0

  shared_preferences: ^2.0.3

  path_provider: ^2.0.1

  uuid: ^4.3.3

  network_info_plus: ^5.0.2

  url_launcher: ^6.0.2

  share_plus: ^8.0.2

  provider: ^6.0.0
  characters: ^1.1.0

  http: ^0.13.6

  slugify: ^2.0.0

  firedart: ^0.9.3

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/graphics/app_icon.png"
  android: true
  ios: true

  adaptive_icon_background: "#FF673AB7"
  adaptive_icon_foreground: "assets/graphics/adaptive_icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Russo One
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf

  assets:
    - assets/graphics/adaptive_icon_foreground.png
    - assets/graphics/wall.png
    - assets/graphics/wall_cross.png
    - assets/animations/mouse.riv
    - assets/animations/cat.riv
    - assets/animations/drag_arrow.gif
    - assets/animations/swipe_arrow.gif
    - assets/animations/remove_arrow.gif
