name: nyanya_rocket
description: Save cute mice from dangerous cats!
homepage: https://github.com/CaramelDunes/nyanya_rocket
publish_to: none

version: 2.0.5+55

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nyanya_rocket_base:
    git:
      url: git://github.com/CaramelDunes/nyanya_rocket_base.git
      ref: feature/nnbd

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

  firebase_core: ^0.8.0-1.0.nullsafety.1
  cloud_firestore: ^0.17.0-1.0.nullsafety.0
  firebase_auth: ^0.21.0-1.1.nullsafety.1
  cloud_functions: ^0.9.1-1.0.nullsafety.1

  rive: ^0.6.8

  font_awesome_flutter: ^9.0.0-nullsafety

  shared_preferences: ^2.0.0-nullsafety

  path_provider: ^2.0.0-nullsafety

  uuid: any

  wifi_info_flutter: ^2.0.0-nullsafety

  url_launcher: ^5.0.0

  share: ^2.0.0-nullsafety.2

  provider: ^5.0.0-nullsafety.2
  characters: ^1.1.0

  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.10+1

#  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "assets/graphics/app_icon.png"
  android: true
  ios: true

  adaptive_icon_background: "#FF673AB7"
  adaptive_icon_foreground: "assets/graphics/adaptive_icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/graphics/adaptive_icon_foreground.png
    - assets/graphics/pit.png
    - assets/graphics/generator.png
    - assets/graphics/wall.png
    - assets/graphics/wall_cross.png
    - assets/graphics/departed_rocket.png
    - assets/animations/mouse_right.riv
    - assets/animations/mouse_up.riv
    - assets/animations/mouse_left.riv
    - assets/animations/mouse_down.riv
    - assets/animations/cat_down.riv
    - assets/animations/cat_up.riv
    - assets/animations/cat_right.riv
    - assets/animations/cat_left.riv
    - assets/animations/drag_arrow.gif
    - assets/animations/swipe_arrow.gif
    - assets/animations/remove_arrow.gif

dependency_overrides:
  intl: 0.17.0