name: nyanya_rocket
description: An open-source game taking inspiration from SEGA's ChuChu Rocket!
author: CaramelDunes
homepage: https://github.com/CaramelDunes/nyanya_rocket

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.15.7

  firebase_core: ^0.3.1+1
  cloud_firestore: ^0.9.5+2

  flare_flutter: ^1.2.3

  font_awesome_flutter: ^8.4.0

  nyanya_rocket_base:
    git:
      url: git://github.com/CaramelDunes/nyanya_rocket_base.git

  shared_preferences: ^0.5.1+1

  path_provider: ^0.5.0+1

  uuid: ^2.0.0

  connectivity: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

  intl_translation: ^0.17.3

flutter_icons:
  image_path: "assets/graphics/app_icon.png"
  android: true
  ios: true

  adaptive_icon_background: "#FF673AB7"
  adaptive_icon_foreground: "assets/graphics/app_icon2.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/graphics/pit.png
    - assets/graphics/generator.png
    - assets/graphics/rocket_blue.png
    - assets/graphics/rocket_red.png
    - assets/graphics/rocket_yellow.png
    - assets/graphics/rocket_green.png
    - assets/graphics/arrow_blue.png
    - assets/graphics/arrow_red.png
    - assets/graphics/arrow_yellow.png
    - assets/graphics/arrow_green.png
    - assets/graphics/arrow_grey.png
    - assets/animations/mouse_right.flr
    - assets/animations/mouse_up.flr
    - assets/animations/mouse_left.flr
    - assets/animations/mouse_down.flr
    - assets/animations/cat_down.flr
    - assets/animations/cat_up.flr
    - assets/animations/cat_right.flr
    - assets/animations/cat_left.flr
    - assets/graphics/wall.png
    - assets/graphics/wall_cross.png
    - assets/graphics/departed_rocket.png
    - assets/graphics/app_icon.png

  fonts:
    - family: Kimberley
      fonts:
        - asset: assets/fonts/kimberley.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
