name: nyanya_rocket
description: An open-source game taking inspiration from SEGA's ChuChu Rocket!
author: CaramelDunes
homepage: https://github.com/CaramelDunes/nyanya_rocket

version: 1.0.0+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nyanya_rocket_base:
    git:
      url: git://github.com/CaramelDunes/nyanya_rocket_base.git

  flutter_localizations:
    sdk: flutter

  intl: ^0.15.7

  firebase_core: ^0.3.1+1
  cloud_firestore: ^0.9.7

  flare_flutter: ^1.3.4

  font_awesome_flutter: ^8.4.0

  shared_preferences: ^0.5.1+2

  path_provider: ^0.5.0+1

  uuid: ^2.0.0

  connectivity: ^0.4.2
  
  url_launcher: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

  intl_translation: ^0.17.3

flutter_icons:
  image_path: "assets/graphics/app_icon.png"
  android: true
  ios: true

  adaptive_icon_background: "#FF673AB7"
  adaptive_icon_foreground: "assets/graphics/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/graphics/adaptive_icon_foreground.png
    - assets/graphics/pit.png
    - assets/graphics/generator.png
    - assets/graphics/rocket_blue.png
    - assets/graphics/rocket_red.png
    - assets/graphics/rocket_yellow.png
    - assets/graphics/rocket_green.png
    - assets/graphics/arrow_blue.png
    - assets/graphics/arrow_red.png
    - assets/graphics/arrow_yellow.png
    - assets/graphics/arrow_green.png
    - assets/graphics/arrow_grey.png
    - assets/graphics/wall.png
    - assets/graphics/wall_cross.png
    - assets/graphics/departed_rocket.png
    - assets/animations/mouse_right.flr
    - assets/animations/mouse_up.flr
    - assets/animations/mouse_left.flr
    - assets/animations/mouse_down.flr
    - assets/animations/cat_down.flr
    - assets/animations/cat_up.flr
    - assets/animations/cat_right.flr
    - assets/animations/cat_left.flr