name: nyanya_rocket
description: Save cute mice from dangerous cats!
homepage: https://github.com/CaramelDunes/nyanya_rocket
publish_to: none

version: 2.0.5+55

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nyanya_rocket_base:
    git:
      url: git://github.com/CaramelDunes/nyanya_rocket_base.git
      ref: feature/nnbd

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_functions: ^1.0.0

  rive: ^0.6.8

  font_awesome_flutter: ^9.0.0-nullsafety

  shared_preferences: ^2.0.3

  path_provider: ^2.0.1

  uuid: ^3.0.1

  wifi_info_flutter: ^2.0.0

  url_launcher: ^6.0.2

  share: ^2.0.0

  provider: ^5.0.0
  characters: ^1.1.0

  http: ^0.13.0

  slugify:
    git:
      url: git://github.com/shyndman/slugify.git

  firedart:
    git:
      url: git://github.com/CaramelDunes/firedart.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/graphics/app_icon.png"
  android: true
  ios: true

  adaptive_icon_background: "#FF673AB7"
  adaptive_icon_foreground: "assets/graphics/adaptive_icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/graphics/adaptive_icon_foreground.png
    - assets/graphics/wall.png
    - assets/graphics/wall_cross.png
    - assets/animations/mouse.riv
    - assets/animations/cat.riv
    - assets/animations/drag_arrow.gif
    - assets/animations/swipe_arrow.gif
    - assets/animations/remove_arrow.gif
